### ISSUE TITLE
Change icons to meaningful ones.

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/x5#11]
![image](https://cloud.githubusercontent.com/assets/5080329/16031928/134dcd62-323c-11e6-8307-a55d7ba1f9ba.png)

Icon on the top is for "Payment",

Icon on the bottom is for payment list.

**Comment by lancelynyrd** [comment]
![sitemap icon](https://cloud.githubusercontent.com/assets/17477197/16114661/fc505df4-33f4-11e6-8844-51fc1c96dd94.png)

Update the icon of payment list.
