### ISSUE TITLE
Payment list design

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/x5#12]
![image](https://cloud.githubusercontent.com/assets/5080329/16033099/18560082-3245-11e6-9f6e-b74acc4dc091.png)

Make it look good on http://work.org/wordpress/enrollment?mode=payment-list

**Comment by lancelynyrd** [comment]
![payment list](https://cloud.githubusercontent.com/assets/17477197/16412614/c3047fac-3d5f-11e6-90fb-bf40bc6a99e1.png)

Updating payment list design
