### ISSUE TITLE
Design enhancement on payment page.

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/x5#18]
![image](https://cloud.githubusercontent.com/assets/5080329/16052628/0ad90728-32a0-11e6-977f-d2bc553662e5.png)

Make the height of the top banner smaller.

Payment page is special.

The pay button should be shown without scroll on desktop.

**Comment by lancelynyrd** [comment]
![enrollmentbanner](https://cloud.githubusercontent.com/assets/17477197/16152410/5d4df19a-34d4-11e6-82e3-ae700341fd69.png)

Update the banner image and make the max height from 280px to 200px.
