### ISSUE TITLE
RWD - The site in RWD is not really good.

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/x5#35]
![image](https://cloud.githubusercontent.com/assets/5080329/16068025/292df62c-32fd-11e6-8de6-0ef8ee0ef166.png)

There is border-radius but  no boundary or space of each box in enrollment. So it does not look good.

**Comment by lancelynyrd** [comment]
![enrollmentrdw](https://cloud.githubusercontent.com/assets/17477197/16115583/7eb22818-33fa-11e6-9669-b00e369c301f.png)

added a space between items and adjust some spaces to fit the whole page in one screen
