### ISSUE TITLE
RWD - scroll watcher ( scroll spy ) is not working properly

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/x5#36]
![image](https://cloud.githubusercontent.com/assets/5080329/16068106/07894926-32fe-11e6-948a-facf3dc70cf0.png)

When the page has been scrolled at the end of the page, the last (bottom) menu of scroll spy should be selected. but it is not.

It happens when the width of the browser(document) reaches around 1200px

**Comment by lancelynyrd** [comment]
Fixed. Added additional space on the footer.
