### ISSUE TITLE
RWD problem - the side( scrollspy ) menu is partly hidden and partly shown. it doesn't look clean.

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/x5#37]
![image](https://cloud.githubusercontent.com/assets/5080329/16068133/4eabbf14-32fe-11e6-8aba-637a76991eae.png)

RWD problem - the side( scrollspy ) menu is partly hidden and partly shown. it doesn't look clean.

The scroll-spy (side) menu shouldn't be shown at the first loading of the site ( or maybe if it must be seen, it should be on the banner, so the side menu wouldn't be partly hidden. )

**Comment by lancelynyrd** [comment]
![spyscroll](https://cloud.githubusercontent.com/assets/17477197/16119174/eab0a636-340c-11e6-9fd0-c76fe249006b.png)

Already have z-index. I just added some font and padding adjustment on 940/1024 and 1280.
