### ISSUE TITLE
RWD - Remove side menu on mobile page.

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/x5#38]
![image](https://cloud.githubusercontent.com/assets/5080329/16068361/3aada25a-3300-11e6-8615-de40756ea702.png)

Remove side menu on mobile page.

**Comment by lancelynyrd** [comment]
![help](https://cloud.githubusercontent.com/assets/17477197/16150865/5dd8da9c-34cc-11e6-8ca4-835a4694dd8e.png)

Fix the RWD of help page banner text and other content alignment and remove the scrollspy on mobile view.
