### ISSUE TITLE
RWD - Menus on Sitemap

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/x5#39]
![image](https://cloud.githubusercontent.com/assets/5080329/16068390/66748c14-3300-11e6-90ab-2dc2963b4d51.png)

Text of the menu are not shown properly.

**Comment by lancelynyrd** [comment]
![sitemap](https://cloud.githubusercontent.com/assets/17477197/16114426/c21cc268-33f3-11e6-984a-c83802cd8ec3.png)

added @media to properly display the links on different width.
