### ISSUE TITLE
RWD - 

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/x5#40]
![image](https://cloud.githubusercontent.com/assets/5080329/16069246/d76dbfb0-3307-11e6-8b52-1b5cd7419f5f.png)

Title of banner on front page is cut.Title of banner on front page is cut.

**Comment by lancelynyrd** [comment]
![banner](https://cloud.githubusercontent.com/assets/17477197/16085011/413318ba-334d-11e6-8563-b12b8dc1b7ba.png)

i added font weight 600 on the title to emphasize the title from the description
