### ISSUE TITLE
Design improvement on payment result page.

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/x5#47]
![image](https://cloud.githubusercontent.com/assets/5080329/16081436/55617eb2-3348-11e6-8ae8-70744ad1ddcb.png)

It is very ugly. make it look good.

**Comment by lancelynyrd** [comment]
![payment result](https://cloud.githubusercontent.com/assets/17477197/16412511/354597f0-3d5f-11e6-9358-3c36dc510fcf.png)

Updating the payment design
