### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/x5#7]
![2016-06-13 22_46_55-work org_wordpress_enrollment - chrome](https://cloud.githubusercontent.com/assets/5080329/16009757/151c6b90-31b9-11e6-953a-d4c4ed920b22.jpg)
- There should be two color on mobile page menu.

**Comment by lancelynyrd** [comment]
![header360](https://cloud.githubusercontent.com/assets/17477197/16041481/284a69c4-3268-11e6-8362-d7a12e86244f.png)

Here is the header design for mobile view.

**Comment by thruthesky** [comment]
![image](https://cloud.githubusercontent.com/assets/5080329/16052711/5f55a7fc-32a0-11e6-94e4-4f0134f9fe54.png)

Give more spaces on the design.

**Comment by lancelynyrd** [comment]
![header360](https://cloud.githubusercontent.com/assets/17477197/16114592/9cb01d94-33f4-11e6-8da5-90af2e3325d2.png)

added space on the logo and close button.  and a little bit padding on the dropdown list
